# Generated by Django 6.1.1 on 2026-10-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='jobs.job'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('ticket', 'purpose'), name='unique_job_per_purpose'),
        ),
        migrations.AddConstraint(
            model_name='jobrun',
            constraint=models.UniqueConstraint(fields=('job', 'attempt'), name='unique_run_per_attempt'),
        ),
    ]
