# Generated by Django 6.1.1 on 2026-10-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='branch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='ci_status',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='job',
            name='head_sha',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='pr_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='pr_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
