# Generated by Django 6.1.1 on 2026-10-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_branch_job_ci_status_job_head_sha_job_pr_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrun',
            name='agent_kind',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='files_changed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='test_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='tests_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='tool_calls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='turns',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
