# Generated by Django 6.1.1 on 2026-10-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobrun_agent_kind_jobrun_files_changed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrun',
            name='proxy_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='proxy_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='proxy_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
