# Generated by Django 6.1.1 on 2026-10-02 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('budget_daily_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_monthly_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manifest_path', models.CharField(max_length=255)),
                ('manifest_hash', models.CharField(max_length=64)),
                ('source_commit', models.CharField(blank=True, max_length=64)),
                ('loaded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('whatsapp', 'whatsapp'), ('email', 'email')], max_length=16)),
                ('value', models.CharField(max_length=320)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client')),
            ],
            options={
                'ordering': ['client__slug', 'kind', 'value'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'value'), name='unique_contact_per_kind')],
            },
        ),
    ]
