# Generated by Django 6.1.1 on 2026-10-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('target', models.CharField(blank=True, max_length=128)),
                ('subject_ref', models.CharField(blank=True, max_length=128)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('manifest_hash', models.CharField(max_length=64)),
                ('action_digest', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('invalidated', 'Invalidated'), ('used', 'Used')], default='pending', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('requested_by', models.CharField(max_length=64)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('decided_by', models.CharField(blank=True, max_length=128)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_source', models.CharField(blank=True, max_length=64)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_by_key', models.CharField(blank=True, max_length=255)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='projects.project')),
            ],
            options={
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved'])), fields=('action_digest',), name='unique_live_approval_per_digest')],
            },
        ),
    ]
