# Generated by Django 6.1.1 on 2026-10-02 15:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('provider', models.CharField(max_length=32)),
                ('service', models.CharField(max_length=32)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveIntegerField(default=0)),
                ('cache_write_tokens', models.PositiveIntegerField(default=0)),
                ('units', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, max_digits=14)),
                ('pricing_version', models.CharField(max_length=32)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('reservation_group', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'usage ledger',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('client', 'Client'), ('project', 'Project'), ('job', 'Job')], max_length=16)),
                ('scope_ref', models.CharField(blank=True, max_length=128)),
                ('period', models.CharField(choices=[('day', 'Day'), ('month', 'Month'), ('run', 'Run')], max_length=8)),
                ('period_key', models.CharField(max_length=16)),
                ('limit_usd', models.DecimalField(decimal_places=6, max_digits=14)),
                ('spent_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14)),
                ('reserved_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14)),
                ('tripped_at', models.DateTimeField(blank=True, null=True)),
                ('trip_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'scope_ref', 'period', 'period_key'), name='unique_budget_window'), models.CheckConstraint(condition=models.Q(('spent_usd__gte', 0), ('reserved_usd__gte', 0)), name='budget_amounts_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='BudgetReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('amount_usd', models.DecimalField(decimal_places=6, max_digits=14)),
                ('purpose', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reconciled', 'Reconciled'), ('released', 'Released'), ('expired', 'Expired')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='budgets.budget')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
