# Generated by Django 6.1.1 on 2026-10-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('clients', '0001_initial'),
        ('jobs', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetreservation',
            name='job_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='jobs.jobrun'),
        ),
        migrations.AddField(
            model_name='usageledger',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client'),
        ),
        migrations.AddField(
            model_name='usageledger',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='usageledger',
            name='job_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage', to='jobs.jobrun'),
        ),
        migrations.AddField(
            model_name='usageledger',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='projects.project'),
        ),
    ]
