# Generated by Django 6.1.1 on 2026-10-02 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(max_length=200, unique=True)),
                ('installation_id', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('protection_ok', models.BooleanField(blank=True, null=True)),
                ('protection_checked_at', models.DateTimeField(blank=True, null=True)),
                ('protection_detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repository_connection', to='projects.project')),
            ],
            options={
                'ordering': ['repository'],
            },
        ),
    ]
