# Generated by Django 6.1.1 on 2026-10-03 18:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'Whatsapp')], max_length=16)),
                ('peer', models.CharField(max_length=320)),
                ('is_owner', models.BooleanField(default=False)),
                ('language', models.CharField(default='es', max_length=8)),
                ('auto_reply_enabled', models.BooleanField(default=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('last_outbound_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='clients.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=3)),
                ('kind', models.CharField(choices=[('inbound', 'Inbound'), ('acknowledgement', 'Acknowledgement'), ('info_request', 'Info Request'), ('status_update', 'Status Update'), ('resolution_notice', 'Resolution Notice'), ('owner_alert', 'Owner Alert')], max_length=24)),
                ('status', models.CharField(choices=[('received', 'Received'), ('pending_approval', 'Pending Approval'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('rejected', 'Rejected')], max_length=20)),
                ('body', models.TextField()),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('action', models.CharField(blank=True, max_length=64)),
                ('risk', models.CharField(blank=True, max_length=16)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='approvals.approval')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('channel', 'peer'), name='unique_conversation_peer'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('external_id',), name='unique_message_external_id'),
        ),
    ]
