# Generated by Django 6.1.1 on 2026-10-02 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.CharField(max_length=64)),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=128)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
