# Generated by Django 6.1.1 on 2026-10-02 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autonomy_level', models.PositiveSmallIntegerField()),
                ('restrict', models.JSONField(default=list)),
                ('maintenance_included', models.JSONField(default=list)),
                ('maintenance_excluded', models.JSONField(default=list)),
                ('sla_critical_first_response_minutes', models.PositiveIntegerField()),
                ('sla_normal_first_response_minutes', models.PositiveIntegerField()),
                ('budget_max_ai_usd_per_run', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_daily_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_monthly_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agent_max_turns', models.PositiveIntegerField()),
                ('agent_timeout_seconds', models.PositiveIntegerField()),
                ('agent_max_retries', models.PositiveIntegerField()),
                ('environments', models.JSONField(default=dict)),
                ('maintenance', models.JSONField(default=dict)),
                ('commands', models.JSONField(default=dict)),
                ('communications', models.JSONField(default=dict)),
                ('manifest_hash', models.CharField(max_length=64)),
                ('global_manifest_hash', models.CharField(max_length=64)),
                ('source_commit', models.CharField(blank=True, max_length=64)),
                ('loaded_at', models.DateTimeField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_policy', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'contract policies',
                'constraints': [models.CheckConstraint(condition=models.Q(('autonomy_level__lte', 4)), name='autonomy_level_range')],
            },
        ),
    ]
