# Generated by Django 6.1.1 on 2026-10-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=64)),
                ('budget_daily_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_monthly_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alert_thresholds_pct', models.JSONField(default=list)),
                ('low_priority_block_pct', models.PositiveSmallIntegerField()),
                ('concurrent_ai_jobs', models.PositiveSmallIntegerField()),
                ('worker_limits', models.JSONField(default=dict)),
                ('approval_default_ttl_minutes', models.PositiveIntegerField()),
                ('max_level_client_projects', models.PositiveSmallIntegerField()),
                ('max_level_internal_projects', models.PositiveSmallIntegerField()),
                ('production_ops_per_hour', models.PositiveSmallIntegerField()),
                ('forbidden', models.JSONField(default=list)),
                ('protected_paths', models.JSONField(default=list)),
                ('manifest_hash', models.CharField(max_length=64)),
                ('source_commit', models.CharField(blank=True, max_length=64)),
                ('loaded_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'global policy',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='global_policy_singleton')],
            },
        ),
    ]
