# Generated by Django 6.1.1 on 2026-10-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_globalpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpolicy',
            name='outbound_messages_per_hour',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
