# Generated by Django 6.1.1 on 2026-10-02 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('repository', models.CharField(max_length=200, unique=True)),
                ('default_branch', models.CharField(max_length=255)),
                ('ownership', models.CharField(choices=[('client', 'Client'), ('internal', 'Internal')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('manifest_path', models.CharField(max_length=255)),
                ('manifest_hash', models.CharField(max_length=64)),
                ('source_commit', models.CharField(blank=True, max_length=64)),
                ('loaded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='clients.client')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
