# Generated by Django 6.1.1 on 2026-10-02 15:17

import django.db.models.deletion
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('external_id', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('sender_kind', models.CharField(blank=True, max_length=16)),
                ('sender_value', models.CharField(blank=True, max_length=320)),
                ('sender_normalized', models.BooleanField(default=False)),
                ('project_hint', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('duplicate_deliveries', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Received'), ('needs_identification', 'Needs Identification'), ('identified', 'Identified'), ('classified', 'Classified'), ('support_only', 'Support Only'), ('reply_draft', 'Reply Draft'), ('sent', 'Sent'), ('code_task', 'Code Task'), ('contract_check', 'Contract Check'), ('investigating', 'Investigating'), ('pull_request', 'Pull Request'), ('needs_quote', 'Needs Quote'), ('waiting_owner', 'Waiting Owner'), ('feature_request', 'Feature Request'), ('needs_clarification', 'Needs Clarification'), ('waiting_client', 'Waiting Client'), ('ci', 'Ci'), ('staging', 'Staging'), ('waiting_approval', 'Waiting Approval'), ('production', 'Production'), ('resolution_notice', 'Resolution Notice'), ('client_notified', 'Client Notified'), ('closed', 'Closed'), ('escalated', 'Escalated'), ('failed', 'Failed')], default='received', max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('correlation_id', models.CharField(db_index=True, default=tickets.models.new_correlation_id, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='clients.client')),
                ('origin_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_of', to='tickets.inboundevent')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inboundevent',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tickets.ticket'),
        ),
        migrations.AddConstraint(
            model_name='inboundevent',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_inbound_event'),
        ),
    ]
